Make fixup: also check if yarn cache is broken and clean it if necessary
If `yarn cache list` fails, this can also lead to weird errors during
fixup, like
```
error /schildichat-desktop/matrix-react-sdk/node_modules/cypress: Command failed.
Exit code: 1
Command: node index.js --exec install
Arguments:
Directory: /schildichat-desktop/matrix-react-sdk/node_modules/cypress
Output:
node:internal/modules/cjs/loader:433
      throw err;
      ^

Error: Cannot find module '/schildichat-desktop/matrix-react-sdk/node_modules/human-signals/build/src/main.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:425:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:638:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Function.Module._load (node:internal/modules/cjs/loader:871:27)
    at Module.require (node:internal/modules/cjs/loader:1098:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/schildichat-desktop/matrix-react-sdk/node_modules/execa/lib/error.js:2:25)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/schildichat-desktop/matrix-react-sdk/node_modules/human-signals
```